name: CI

on:
  push:
    branches:
      - dev

job:
  pipeline-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.3.0"
          cache: yarn
      - name: install dependencies
        run: yarn install
      - name: build application
        run: yarn build
      - name: lint
        run: yarn lint
      - name: unit test
        run: yarn test:unit
